languageCode = "en-us"
title = "Software Engineering Leader"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"


[params]
    description = "Software Engineering Leader in Berlin"
    footer = "&copy; [E.S.](https://saboteur.me) 2017 -- 2022 | [LinkedIn](https://www.linkedin.com/in/soynov/) | [Github](https://github.com/ZloeSabo)"
